### ISSUE TITLE
You've already activated this request

### ISSUE THREAD

**Issue by ForbesLindesay** [mrjoelkemp/packagestats-issues#4]
I keep getting that error whenever I enter my email and npm username

**Comment by mrjoelkemp** [comment]
@ForbesLindesay Thanks for the report and apologies for the trouble. I've fixed the issue and registered you. Since you're one of the larger authors in the system, I'd like to make sure that the batch-processing system can handle the load before unlocking your stats. I intend to verify this tonight and will ping you when all is well. 

Cheers!
